### ISSUE TITLE
ModuleNotFoundError: No module named 'yaml'

### ISSUE THREAD

**Issue by kadirnar** [canturan10/satellighte#12] opened 2022-08-13 16:13 UTC
Os: Windows 11
```
git clone https://github.com/canturan10/satellighte.git
cd satellighte
conda create -n satellighte pytnon=3.8 -y
pip install -e ".[all]"
```
Error Message:
```
File ...\satellighte\satellighte\core.py", line 8, in <module>
     import yaml
     ModuleNotFoundError: No module named 'yaml'
```
Why are you using this library?
- [torchaudio](https://github.com/canturan10/satellighte/blob/master/requirements.txt#L8)

**Comment by canturan10** [comment] 2022-08-13 16:28
Hello There 👋

First of all, the command you have written is incorrect. Most likely there was a mistake while writing it here, but let's start there anyway.
You should update this line `conda create -n satellighte pytnon=3.8 -y` like this `conda create -n satellighte python=3.8 -y`

Then, I think there was a problem during the installation of the packages.
You can install from pypi with the following command.
`pip install satellighte`
or   
In order to create the necessary environment properly
`pip install -r requirements.txt`
You can try after that. 
This way we can quickly make it work for you. But I will look into the cause of this error.

And finally, there are developers who only update their requirement files. I thought about them while I was doing this project :) I am waiting for the lucky person who will contribute to the project only in this way. Otherwise, of course, I know the library isn't necessary :)

Thank you.

**Comment by canturan10** [comment] 2022-08-13 17:16
After examining it in detail, I solved the problem. You can try again now. What I wrote before will also be useful. But now the problem is solved. That's why I'm closing the issue.

Thank you.

**Closed by canturan10** 2022-08-13 17:16 UTC

**Comment by kadirnar** [comment] 2022-08-13 17:19
Thank you. The problem was the solution.
